/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ImageResponse: (typeof import("next/og"))["ImageResponse"];
  const Link: (typeof import("next/link"))["default"];
  const NextImage: (typeof import("next/image"))["default"];
  const NextRequest: (typeof import("next/server"))["NextRequest"];
  const NextResponse: (typeof import("next/server"))["NextResponse"];
  const Page2NavItemsTextArr: (typeof import("./src/constants/index"))["Page2NavItemsTextArr"];
  const Page3NavItemsTextArr: (typeof import("./src/constants/index"))["Page3NavItemsTextArr"];
  const Script: (typeof import("next/script"))["default"];
  const createRef: (typeof import("react"))["createRef"];
  const forwardRef: (typeof import("react"))["forwardRef"];
  const lazy: (typeof import("react"))["lazy"];
  const memo: (typeof import("react"))["memo"];
  const redirect: (typeof import("next/navigation"))["redirect"];
  const startTransition: (typeof import("react"))["startTransition"];
  const useCallback: (typeof import("react"))["useCallback"];
  const useContext: (typeof import("react"))["useContext"];
  const useDebugValue: (typeof import("react"))["useDebugValue"];
  const useDeferredValue: (typeof import("react"))["useDeferredValue"];
  const useEffect: (typeof import("react"))["useEffect"];
  const useId: (typeof import("react"))["useId"];
  const useImperativeHandle: (typeof import("react"))["useImperativeHandle"];
  const useInsertionEffect: (typeof import("react"))["useInsertionEffect"];
  const useLayoutEffect: (typeof import("react"))["useLayoutEffect"];
  const useMemo: (typeof import("react"))["useMemo"];
  const useMetadata: (typeof import("./src/utils/index"))["useMetadata"];
  const useReducer: (typeof import("react"))["useReducer"];
  const useRef: (typeof import("react"))["useRef"];
  const useState: (typeof import("react"))["useState"];
  const useSyncExternalStore: (typeof import("react"))["useSyncExternalStore"];
  const useTransition: (typeof import("react"))["useTransition"];
  const userAgent: (typeof import("next/server"))["userAgent"];
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ComponentProps } from "react";
  import("react");
  // @ts-ignore
  export type { Metadata, ResolvingMetadata } from "next";
  import("next");
  // @ts-ignore
  export type {
    UnoAttriesObj,
    KeyOfUnoAttri,
    AttributifyNames,
  } from "./src/constants/unocss";
  import("./src/constants/unocss");
}
