import type { Metadata } from "next";
// 后续页面的本步骤使用自动引入的 `useMetadata` util hook 进行配置。
export const metadata: Metadata = {
  title: {
    template: "Figma Imitate | %s",
    default: "Figma Imitate",
  },
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";
import "@/app/globals.css";
const inter = Inter({ subsets: ["latin"] });

import RootLayoutNav from "@/app/_components/RootLayoutNav";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 项目页面导航 */}
        {/* <RootLayoutNav /> */}
        {/* 根目录子元素展示槽位 */}
        <div>{children}</div>
      </body>
    </html>
  );
}
